server:
  port: ${server_port:8080}
  servlet:
    context-path: /api
spring:
  application:
    name: person_service
  jpa:
    show-sql: true
  datasource:
    url: jdbc:h2:mem:personsDb
    username: testUser
    password: testUser
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2
orika:
  mapNulls: true
  name: mainOrika
