server:
  port: ${server_port:8080}
  servlet:
    context-path: /api
spring:
  application:
    name: person_service
  datasource:
    url: jdbc:h2:mem:personsDb
    username: testUser
    password: testUser
    driverClassName: org.h2.Driver

orika:
  mapNulls: true
  name: mainOrika
